version: "3"

services:
  home:
    restart: always
    build: ./home

  app1:
    restart: always
    build: ./service1

  app2:
    restart: always
    build: ./service2

  proxy:
    restart: always
    build: ./proxy
    ports:
      - "80:80"

    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
